(() => {
  const API = "/api/v1";
  const state = { token: sessionStorage.getItem("nepres_doctor_token"), user: null, view: "overview", patients: [], plans: [], templates: [], currentPatient: null, showInactivePlans: false, patientFilter: "all" };
  const $ = (selector) => document.querySelector(selector);
  const icon = () => window.lucide?.createIcons({ attrs: { "stroke-width": 1.75 } });
  function toast(message) { let element = document.querySelector("#doctor-toast"); if (!element) { element = document.createElement("div"); element.id = "doctor-toast"; element.className = "toast"; element.setAttribute("role", "status"); document.body.append(element); } element.textContent = message; element.classList.remove("is-hidden"); window.clearTimeout(element.timeout); element.timeout = window.setTimeout(() => element.classList.add("is-hidden"), 3200); }
  const escape = (value) => String(value ?? "—").replace(/[&<>'"]/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[character]));
  async function request(path, options = {}) {
    const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.token}`, ...(options.headers || {}) } });
    if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || "Не удалось выполнить запрос"); }
    return response.status === 204 ? null : response.json();
  }
  function setScreen(authenticated) { $("#login-screen").classList.toggle("is-hidden", authenticated); $("#doctor-app").classList.toggle("is-hidden", !authenticated); icon(); }
  function empty(title, text, iconName) { return `<section class="panel"><div class="empty-state"><i data-lucide="${iconName}"></i><h2>${title}</h2><p>${text}</p></div></section>`; }
  function loading() { $("#page-content").innerHTML = `<section class="panel"><div class="loading-state"><i data-lucide="loader-circle"></i><h2>Загружаем данные</h2><p>Пожалуйста, подождите.</p></div></section>`; icon(); }
  function activePlansByPatient() { const result = new Map(); state.plans.filter((plan) => plan.status === "active").forEach((plan) => { if (!result.has(plan.patient_id)) result.set(plan.patient_id, plan); }); return result; }
  function patientFor(plan) { return state.patients.find((patient) => patient.id === plan.patient_id); }
  function needsAttention(plan) { return Boolean(plan) && (!plan.last_activity_at || (plan.today_total_count > 0 && plan.today_completed_count < plan.today_total_count)); }
  function patientStatus(plan) { if (!plan) return ["Без активного курса", "is-neutral"]; if (!plan.last_activity_at) return ["Нет активности", "is-danger"]; if (plan.today_total_count > plan.today_completed_count) return ["Есть задания на сегодня", "is-warning"]; return ["Выполняет без задержек", "is-success"]; }
  function renderOverview() {
    const total = state.patients.length;
    if (!total) { $("#page-content").innerHTML = `<section class="overview">${empty("Рабочее пространство готово", "Создайте первую карточку пациента. Затем назначьте ему цифровой маршрут лечения и отправьте ссылку.", "clipboard-plus")}</section>`; icon(); return; }
    const activeByPatient = activePlansByPatient(); const activePlans = [...activeByPatient.values()]; const attention = activePlans.filter(needsAttention); const withoutCourse = state.patients.filter((patient) => !activeByPatient.has(patient.id));
    const todayTotal = activePlans.reduce((sum, plan) => sum + plan.today_total_count, 0); const todayDone = activePlans.reduce((sum, plan) => sum + plan.today_completed_count, 0); const todayPercent = todayTotal ? Math.round(todayDone / todayTotal * 100) : null;
    const recent = activePlans.filter((plan) => plan.last_activity_at).sort((left, right) => new Date(right.last_activity_at) - new Date(left.last_activity_at)).slice(0, 4);
    const attentionRows = attention.slice(0, 4).map((plan) => { const patient = patientFor(plan); const reason = !plan.last_activity_at ? "Пациент ещё не отмечал выполнение" : `${Math.max(0, plan.today_total_count - plan.today_completed_count)} задан. осталось сегодня`; return `<button class="attention-card ${!plan.last_activity_at ? "is-danger" : ""}" data-patient-id="${plan.patient_id}"><span><strong>${escape(patient?.full_name)}</strong><p>${escape(reason)}</p></span><i data-lucide="chevron-right"></i></button>`; }).join("");
    const recentRows = recent.map((plan) => { const patient = patientFor(plan); return `<button class="activity-row" data-patient-id="${plan.patient_id}"><span class="activity-avatar">${escape(patient?.first_name?.charAt(0) || "П")}</span><span class="activity-copy"><strong>${escape(patient?.full_name)}</strong><small>${escape(plan.title)} · ${formatDateTime(plan.last_activity_at)}</small></span><span class="status-badge is-success">${plan.completed_count}/${plan.total_count}</span></button>`; }).join("");
    $("#page-content").innerHTML = `<section class="overview"><section class="today-board"><div class="today-copy"><p class="eyebrow">Сегодня</p><h2>${activePlans.length} пациентов проходят курс</h2><p>Назначено ${todayTotal} действий · выполнено ${todayDone}${todayPercent === null ? "" : ` (${todayPercent}%)`}</p><button class="button button-primary" data-action="open-attention"><i data-lucide="siren"></i>Открыть очередь внимания</button></div><div class="today-numbers"><article><strong>${Math.max(0, activePlans.length - attention.length)}</strong><span>выполняют без задержек</span></article><article class="is-attention"><strong>${attention.length}</strong><span>требуют внимания</span></article><article><strong>${withoutCourse.length}</strong><span>без активного курса</span></article></div></section><div class="stats-grid"><button class="stat-card" data-action="open-attention"><span class="stat-label">Требуют внимания</span><strong class="stat-value">${attention.length}</strong><small>Нет активности или есть незавершённые задания</small></button><button class="stat-card" data-action="open-patients"><span class="stat-label">На сегодня</span><strong class="stat-value">${todayPercent === null ? "—" : `${todayPercent}%`}</strong><small>${todayDone} из ${todayTotal} заданий выполнено</small></button><button class="stat-card" data-action="open-without-course"><span class="stat-label">Без активного курса</span><strong class="stat-value">${withoutCourse.length}</strong><small>Нужно назначить лечение</small></button></div><div class="overview-columns"><section class="panel"><div class="panel-heading"><h2>Требуют внимания</h2><button class="text-action" data-action="open-attention">Вся очередь</button></div><div class="attention-list">${attentionRows || `<div class="panel-placeholder"><i data-lucide="circle-check-big"></i><p>Сейчас нет пациентов, требующих внимания.</p></div>`}</div></section><section class="panel"><div class="panel-heading"><h2>Последняя активность</h2><button class="text-action" data-action="open-plans">Планы лечения</button></div><div class="activity-list">${recentRows || `<div class="panel-placeholder"><i data-lucide="activity"></i><p>Отметки пациентов появятся здесь после выполнения заданий.</p></div>`}</div></section></div><section class="quick-actions"><h2>Быстрые действия</h2><div><button class="button button-primary" data-action="new-patient"><i data-lucide="user-plus"></i>Новый пациент</button><button class="button button-secondary" data-action="open-without-course"><i data-lucide="calendar-plus"></i>Назначить курс</button><button class="button button-secondary" data-action="open-attention"><i data-lucide="siren"></i>Очередь внимания</button></div></section></section>`;
    icon();
  }
  function renderPatients() {
    const query = $("#search-input").value.trim().toLowerCase();
    const plansByPatient = activePlansByPatient();
    const visible = state.patients.filter((patient) => `${patient.first_name} ${patient.last_name} ${patient.phone || ""} ${patient.email || ""}`.toLowerCase().includes(query)).filter((patient) => state.patientFilter === "attention" ? needsAttention(plansByPatient.get(patient.id)) : state.patientFilter === "without-course" ? !plansByPatient.has(patient.id) : true);
    const row = (patient) => `<button class="table-row patient-row" type="button" data-patient-id="${patient.id}" aria-label="Открыть подробности: ${escape(patient.full_name)}"><span class="table-cell is-wide" title="${escape(patient.full_name)}">${escape(patient.full_name)}</span><span class="table-cell">${escape(patient.sex === "male" ? "Мужской" : patient.sex === "female" ? "Женский" : "Не указан")}</span><span class="table-cell">${escape(patient.phone || patient.email)}</span><span class="table-cell" title="${escape(patient.diagnosis)}" aria-label="Диагноз: ${escape(patient.diagnosis)}">${escape(patient.diagnosis)}</span></button>`;
    const title = state.patientFilter === "attention" ? "Очередь внимания" : state.patientFilter === "without-course" ? "Без активного курса" : "Мои пациенты";
    $("#page-content").innerHTML = `<section class="patients-view"><section class="panel"><div class="panel-heading"><h2>${title}</h2><p>${visible.length} из ${state.patients.length}</p></div>${visible.length ? `<div class="table"><div class="table-row table-head"><div class="table-cell is-wide">Пациент</div><div class="table-cell">Пол</div><div class="table-cell">Контакт</div><div class="table-cell">Диагноз / повод</div></div>${visible.map(row).join("")}</div>` : empty(query ? "Ничего не найдено" : "Пациентов пока нет", query ? "Попробуйте изменить запрос поиска." : "Создайте первую карточку пациента — она будет привязана к вашему профилю.", "users-round").replace('<section class="panel">', '').replace('</section>', '')}</section></section>`;
    icon();
  }
  const formatDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("ru-RU") : "Не указано";
  const formatDateTime = (value) => value ? new Date(value).toLocaleString("ru-RU", { dateStyle: "short", timeStyle: "short" }) : "";
  const detailField = (label, value) => `<div class="detail-field"><dt>${label}</dt><dd>${escape(value || "Не указано")}</dd></div>`;
  function planSummary(plan) { return `<article class="treatment-card"><div><strong>${escape(plan.title)}</strong><span>${escape(plan.status)} · ${plan.duration_days || "—"} дней · старт ${formatDate(plan.starts_on)}</span></div><button class="compact-button" data-open-plan="${plan.id}">Открыть</button></article>`; }
  function renderTreatments() {
    const visible = state.plans.filter((plan) => state.showInactivePlans || plan.status === "active");
    const planRow = (plan) => { const patient = patientFor(plan); const percent = plan.total_count ? Math.round(plan.completed_count / plan.total_count * 100) : 0; const today = plan.today_total_count ? `${plan.today_completed_count} из ${plan.today_total_count} сегодня` : "Нет заданий на сегодня"; return `<article class="plan-registry-row"><div class="plan-registry-copy"><span class="status-badge ${plan.status === "active" ? "is-success" : "is-neutral"}">${plan.status === "active" ? "Активен" : escape(plan.status === "paused" ? "На паузе" : "Завершён")}</span><strong>${escape(plan.title)}</strong><span>${escape(patient?.full_name || "Пациент не найден")} · день ${plan.today_day_number || "—"} из ${plan.duration_days || "—"}</span></div><div class="plan-progress"><strong>${percent}%</strong><span>${plan.completed_count} из ${plan.total_count} за курс</span><span>${today}</span></div><div class="plan-row-actions"><span>${plan.last_activity_at ? `Активность ${formatDateTime(plan.last_activity_at)}` : "Нет активности"}</span><button class="compact-button" data-open-plan="${plan.id}">Открыть</button></div></article>`; };
    $("#page-content").innerHTML = `<section class="treatments-view"><section class="panel"><div class="panel-heading plan-registry-heading"><div><h2>${state.showInactivePlans ? "Все планы лечения" : "Активные планы лечения"}</h2><p>${visible.length} из ${state.plans.length}</p></div><button class="filter-toggle ${state.showInactivePlans ? "is-active" : ""}" id="inactive-plans-toggle" aria-pressed="${state.showInactivePlans}"><i data-lucide="check"></i><span>Показывать неактивные</span></button></div><div class="plan-registry">${visible.length ? visible.map(planRow).join("") : `<div class="panel-placeholder"><i data-lucide="clipboard-list"></i><h2>Активных планов нет</h2><p>Назначьте лечение пациенту — оно появится в этом списке.</p></div>`}</div></section></section>`;
    icon();
  }
  async function showPatientDetail(patient) {
    if (!patient) return;
    state.currentPatient = patient;
    try { state.plans = await request("/treatment-plans"); } catch (_) { state.plans = []; }
    const plans = state.plans.filter((plan) => plan.patient_id === patient.id);
    const age = patient.birth_date ? Math.floor((Date.now() - new Date(`${patient.birth_date}T00:00:00`)) / 31557600000) : null;
    const contactActions = `${patient.phone ? `<a class="compact-button" href="tel:${escape(patient.phone)}"><i data-lucide="phone"></i>Позвонить</a>` : ""}${patient.email ? `<a class="compact-button" href="mailto:${escape(patient.email)}"><i data-lucide="mail"></i>Написать</a>` : ""}`;
    const risks = `${patient.allergies ? `<div class="risk-card is-danger"><strong>Аллергии</strong><span>${escape(patient.allergies)}</span></div>` : ""}${patient.contraindications ? `<div class="risk-card is-warning"><strong>Противопоказания</strong><span>${escape(patient.contraindications)}</span></div>` : ""}${patient.emergency_contact ? `<div class="risk-card"><strong>Экстренный контакт</strong><span>${escape(patient.emergency_contact)}</span></div>` : ""}`;
    const magicLink = patient.magic_link_token ? `${location.origin}/p/${patient.magic_link_token}` : null;
    $("#patient-detail-title").textContent = patient.full_name;
    $("#patient-detail-content").innerHTML = `<div class="patient-identity"><span class="patient-avatar">${escape(patient.first_name?.charAt(0))}</span><div><h3>${escape(patient.full_name)}</h3><p>${age === null ? "Возраст не указан" : `${age} лет`} · дата рождения ${formatDate(patient.birth_date)}</p></div></div><div class="editor-actions detail-contact-actions">${contactActions}</div>${magicLink ? `<section class="magic-link-card"><div><span class="eyebrow">Ссылка для пациента</span><a href="${escape(magicLink)}" target="_blank" rel="noreferrer" title="${escape(magicLink)}">${escape(magicLink)}</a></div><div class="magic-link-actions"><a class="compact-button" href="${escape(magicLink)}" target="_blank" rel="noreferrer"><i data-lucide="external-link"></i>Открыть</a><button class="compact-button" type="button" data-copy-magic-link="${escape(magicLink)}"><i data-lucide="copy"></i>Копировать</button></div></section>` : ""}${risks ? `<section class="risk-list">${risks}</section>` : ""}<section class="detail-section"><div class="detail-actions"><h3>Лечение</h3><button class="compact-button" id="assign-treatment"><i data-lucide="plus"></i>Назначить</button></div><div class="treatment-list">${plans.length ? plans.map(planSummary).join("") : `<p class="detail-meta">Лечение пока не назначено.</p>`}</div></section><section class="detail-section"><h3>Основные данные</h3><dl class="detail-grid">${detailField("Пол", patient.sex === "male" ? "Мужской" : patient.sex === "female" ? "Женский" : patient.sex === "other" ? "Другой" : "Не указан")}${detailField("Телефон", patient.phone)}${detailField("Email", patient.email)}</dl></section><section class="detail-section"><h3>Медицинский контекст</h3><dl class="detail-grid">${detailField("Диагноз / повод обращения", patient.diagnosis)}${detailField("Дата диагноза", formatDate(patient.diagnosis_date))}${detailField("Начало лечения", formatDate(patient.treatment_start_date))}${detailField("Рост", patient.height_cm ? `${patient.height_cm} см` : null)}${detailField("Вес", patient.weight_kg ? `${patient.weight_kg} кг` : null)}${detailField("Сопутствующие заболевания", patient.comorbidities)}${detailField("Заметки врача", patient.doctor_notes)}</dl></section><p class="detail-meta">Карточка создана ${formatDate(patient.created_at?.slice(0, 10))}. Согласие зафиксировано: ${formatDate(patient.data_processing_consent_at?.slice(0, 10))}.</p>`;
    $("#patient-detail-layer").classList.remove("is-hidden"); icon();
  }
  function hidePatientDetail() { $("#patient-detail-layer").classList.add("is-hidden"); }
  async function showPlanForm() {
    state.templates = await request("/treatment-templates");
    $("#plan-template").innerHTML = `<option value="">Индивидуальный план без шаблона</option>${state.templates.map((template) => `<option value="${template.id}">${escape(template.title)}${template.default_duration_days ? ` · ${template.default_duration_days} дн.` : ""}</option>`).join("")}`;
    $("#plan-form").reset(); $("#plan-form [name=starts_on]").value = new Date().toISOString().slice(0, 10); $("#plan-form-error").textContent = ""; $("#plan-form-layer").classList.remove("is-hidden"); icon();
  }
  function hidePlanForm() { $("#plan-form-layer").classList.add("is-hidden"); }
  async function showPlanEditor(planId) {
    const plan = await request(`/treatment-plans/${planId}`);
    $("#plan-editor-title").textContent = plan.title;
    const feedback = (item) => item.completed ? `<div class="plan-feedback"><i data-lucide="check-circle-2"></i><span>Отмечено ${formatDateTime(item.completed_at)}${item.patient_answer ? `<br>Ответ: ${escape(item.patient_answer)}` : ""}</span></div>` : `<div class="plan-feedback is-waiting"><i data-lucide="clock-3"></i><span>Пациент ещё не отметил выполнение</span></div>`;
    const dayMarkup = plan.days.map((day) => `<article class="plan-day"><h3>День ${day.day_number}${day.title ? ` · ${escape(day.title)}` : ""}</h3>${day.blocks.map((block) => `<div class="plan-item"><strong>${escape(block.title)}</strong>${block.question ? `<span>Вопрос: ${escape(block.question)}</span>` : ""}${feedback(block)}</div>`).join("")}${day.medications.map((medication) => `<div class="plan-item"><strong>${escape(medication.medication_name)}</strong><span>${escape(medication.dosage || "Дозировка не указана")} ${medication.scheduled_time || ""}</span>${feedback(medication)}</div>`).join("")}${!day.blocks.length && !day.medications.length ? `<div class="plan-item">На этот день пока ничего не назначено.</div>` : ""}</article>`).join("");
    const quickDays = plan.days.slice(0, 5).map((day) => `<button class="day-choice ${day.day_number === 1 ? "is-selected" : ""}" type="button" data-day="${day.day_number}">${day.day_number}</button>`).join("");
    const dayPicker = () => `<div class="day-picker" data-day-picker><input type="hidden" name="day_number" value="1" /><span class="day-picker-label">День плана</span><div class="day-choice-row">${quickDays}</div><label class="custom-day">Другой день<input class="input day-custom" type="number" min="1" max="365" placeholder="№" inputmode="numeric" /></label><span class="field-hint">Если указать день за пределами плана, курс автоматически продлится.</span></div>`;
    $("#plan-editor-content").innerHTML = `<form class="inline-form" id="plan-status-form"><label class="field-label">Название<input class="input" name="title" value="${escape(plan.title)}" /></label><label class="field-label">Статус<select class="input" name="status"><option value="active" ${plan.status === "active" ? "selected" : ""}>Активен</option><option value="paused" ${plan.status === "paused" ? "selected" : ""}>На паузе</option><option value="completed" ${plan.status === "completed" ? "selected" : ""}>Завершён</option></select></label><button class="button button-secondary" type="submit">Сохранить изменения</button></form><section class="detail-section"><h3>Добавить в план</h3><div class="editor-actions"><form class="inline-form" id="add-block-form">${dayPicker()}<label class="field-label">Тип блока<select class="input" name="block_type"><option value="exercise">Упражнение</option><option value="text">Текст</option><option value="video">Видео</option><option value="pdf">PDF</option><option value="question">Вопрос</option><option value="checklist">Чеклист</option><option value="photo">Фото</option><option value="link">Ссылка</option></select></label><label class="field-label">Название<input class="input" name="title" required /></label><label class="field-label">Вопрос пациенту<input class="input" name="question" /></label><button class="compact-button" type="submit">Добавить задание</button></form><form class="inline-form" id="add-medication-form">${dayPicker()}<label class="field-label">Лекарство<input class="input" name="medication_name" required /></label><label class="field-label">Дозировка<input class="input" name="dosage" /></label><label class="field-label">Время<input class="input" name="scheduled_time" type="time" /></label><label class="field-label">Вопрос пациенту<input class="input" name="question" /></label><button class="compact-button" type="submit">Добавить приём</button></form></div></section><section class="detail-section"><h3>Дни плана</h3><div class="plan-days">${dayMarkup}</div></section>`;
    $("#plan-editor-layer").dataset.planId = plan.id; $("#plan-editor-layer").classList.remove("is-hidden"); icon();
  }
  function hidePlanEditor() { $("#plan-editor-layer").classList.add("is-hidden"); }
  async function renderCurrent() {
    const copy = state.view === "overview" ? ["Обзор", "Рабочее пространство"] : state.view === "treatments" ? ["Планы лечения", "Лечение"] : ["Мои пациенты", "Пациенты"];
    $("#page-title").textContent = copy[0]; $("#page-section").textContent = copy[1];
    document.querySelectorAll("[data-view]").forEach((item) => item.classList.toggle("is-active", item.dataset.view === state.view));
    $("#search-input").closest(".search-control").classList.toggle("is-hidden", state.view !== "patients");
    loading();
    try { const [patients, plans] = await Promise.all([request("/patients"), request("/treatment-plans")]); state.patients = patients; state.plans = plans; if (state.view === "overview") renderOverview(); else if (state.view === "treatments") renderTreatments(); else renderPatients(); } catch (error) { $("#page-content").innerHTML = empty("Не удалось загрузить данные", error.message, "triangle-alert"); icon(); }
  }
  function showModal() { $("#patient-form").reset(); $("#patient-error").textContent = ""; $("#modal-layer").classList.remove("is-hidden"); icon(); }
  function hideModal() { $("#modal-layer").classList.add("is-hidden"); }
  $("#login-form").addEventListener("submit", async (event) => {
    event.preventDefault(); const button = $("#login-button"); button.disabled = true; button.querySelector("span").textContent = "Входим…"; $("#login-error").textContent = ""; $("#admin-login-link").classList.add("is-hidden");
    try {
      const response = await fetch(`${API}/auth/login`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) });
      if (!response.ok) throw new Error("Проверьте логин и пароль.");
      state.token = (await response.json()).access_token; state.user = await request("/auth/me");
      if (state.user.is_admin) { $("#admin-login-link").classList.remove("is-hidden"); throw new Error("Этот кабинет предназначен для врача. Перейдите в админ-панель."); }
      sessionStorage.setItem("nepres_doctor_token", state.token); $("#account-name").textContent = state.user.full_name; $("#account-avatar").textContent = state.user.full_name.charAt(0).toUpperCase(); setScreen(true); renderCurrent();
    } catch (error) { sessionStorage.removeItem("nepres_doctor_token"); state.token = null; $("#login-error").textContent = error.message; } finally { button.disabled = false; button.querySelector("span").textContent = "Войти"; }
  });
  $("#password-toggle").addEventListener("click", () => { const input = $("#password"); const visible = input.type === "text"; input.type = visible ? "password" : "text"; $("#password-toggle").setAttribute("aria-label", visible ? "Показать пароль" : "Скрыть пароль"); $("#password-toggle").innerHTML = `<i data-lucide="${visible ? "eye" : "eye-off"}"></i>`; icon(); });
  document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { state.view = button.dataset.view; state.patientFilter = "all"; document.querySelectorAll("[data-view]").forEach((item) => item.classList.toggle("is-active", item.dataset.view === state.view)); renderCurrent(); }));
  $("#refresh-button").addEventListener("click", renderCurrent); $("#search-input").addEventListener("input", () => { if (state.view === "patients") renderPatients(); });
  $("#new-patient-button").addEventListener("click", showModal); $("#modal-close").addEventListener("click", hideModal); $("#modal-cancel").addEventListener("click", hideModal); $("#modal-layer").addEventListener("click", (event) => { if (event.target === event.currentTarget) hideModal(); });
  $("#page-content").addEventListener("click", (event) => { const row = event.target.closest("[data-patient-id]"); const plan = event.target.closest("[data-open-plan]"); const go = event.target.closest("[data-go]"); const action = event.target.closest("[data-action]"); const inactiveToggle = event.target.closest("#inactive-plans-toggle"); const retry = event.target.closest("#retry-load"); if (row) showPatientDetail(state.patients.find((patient) => patient.id === Number(row.dataset.patientId))); if (plan) showPlanEditor(plan.dataset.openPlan); if (inactiveToggle) { state.showInactivePlans = !state.showInactivePlans; renderTreatments(); } if (action) { if (action.dataset.action === "new-patient") showModal(); if (action.dataset.action === "open-attention") { state.view = "patients"; state.patientFilter = "attention"; renderCurrent(); } if (action.dataset.action === "open-without-course") { state.view = "patients"; state.patientFilter = "without-course"; renderCurrent(); } if (action.dataset.action === "open-patients") { state.view = "patients"; state.patientFilter = "all"; renderCurrent(); } if (action.dataset.action === "open-plans") { state.view = "treatments"; renderCurrent(); } } if (go) { state.view = go.dataset.go; state.patientFilter = go.dataset.filter || "all"; renderCurrent(); } if (retry) renderCurrent(); });
  $("#patient-detail-close").addEventListener("click", hidePatientDetail); $("#patient-detail-layer").addEventListener("click", (event) => { if (event.target === event.currentTarget) hidePatientDetail(); });
  $("#patient-detail-content").addEventListener("click", async (event) => { if (event.target.closest("#assign-treatment")) showPlanForm(); const plan = event.target.closest("[data-open-plan]"); if (plan) showPlanEditor(plan.dataset.openPlan); const copyButton = event.target.closest("[data-copy-magic-link]"); if (copyButton) { try { await navigator.clipboard.writeText(copyButton.dataset.copyMagicLink); copyButton.innerHTML = `<i data-lucide="check"></i>Скопировано`; icon(); window.setTimeout(() => { copyButton.innerHTML = `<i data-lucide="copy"></i>Копировать`; icon(); }, 2000); } catch (_) { copyButton.innerHTML = `<i data-lucide="copy-x"></i>Скопируйте вручную`; icon(); } } });
  $("#plan-form-close").addEventListener("click", hidePlanForm); $("#plan-form-cancel").addEventListener("click", hidePlanForm); $("#plan-form-layer").addEventListener("click", (event) => { if (event.target === event.currentTarget) hidePlanForm(); });
  $("#plan-form").addEventListener("submit", async (event) => {
    event.preventDefault(); const fields = Object.fromEntries(new FormData(event.currentTarget)); fields.patient_id = state.currentPatient.id; fields.template_id = fields.template_id ? Number(fields.template_id) : null; fields.duration_days = fields.duration_days ? Number(fields.duration_days) : null;
    try { await request("/treatment-plans", { method: "POST", body: JSON.stringify(fields) }); hidePlanForm(); toast("Лечение назначено пациенту."); await showPatientDetail(state.currentPatient); } catch (error) { $("#plan-form-error").textContent = error.message; }
  });
  $("#plan-editor-close").addEventListener("click", hidePlanEditor); $("#plan-editor-layer").addEventListener("click", (event) => { if (event.target === event.currentTarget) hidePlanEditor(); });
  $("#plan-editor-content").addEventListener("click", (event) => { const button = event.target.closest("[data-day]"); if (!button) return; const picker = button.closest("[data-day-picker]"); picker.querySelector("[name=day_number]").value = button.dataset.day; picker.querySelectorAll("[data-day]").forEach((item) => item.classList.toggle("is-selected", item === button)); picker.querySelector(".day-custom").value = ""; });
  $("#plan-editor-content").addEventListener("input", (event) => { if (!event.target.matches(".day-custom")) return; const picker = event.target.closest("[data-day-picker]"); const input = picker.querySelector("[name=day_number]"); if (event.target.validity.valid && event.target.value) { input.value = event.target.value; picker.querySelectorAll("[data-day]").forEach((item) => item.classList.remove("is-selected")); } });
  $("#plan-editor-content").addEventListener("submit", async (event) => { event.preventDefault(); const planId = $("#plan-editor-layer").dataset.planId; const data = Object.fromEntries(new FormData(event.target)); if (event.target.id === "plan-status-form") await request(`/treatment-plans/${planId}`, { method: "PATCH", body: JSON.stringify(data) }); if (event.target.id === "add-block-form") { const day = data.day_number; delete data.day_number; data.question ||= null; await request(`/treatment-plans/${planId}/days/${day}/blocks`, { method: "POST", body: JSON.stringify(data) }); } if (event.target.id === "add-medication-form") { const day = data.day_number; delete data.day_number; data.dosage ||= null; data.scheduled_time ||= null; data.question ||= null; await request(`/treatment-plans/${planId}/days/${day}/medications`, { method: "POST", body: JSON.stringify(data) }); } await showPlanEditor(planId); });
  $("#patient-form").addEventListener("submit", async (event) => {
    event.preventDefault(); const button = $("#patient-submit"); const fields = Object.fromEntries(new FormData(event.currentTarget));
    ["phone","email","height_cm","weight_kg","diagnosis_date","contraindications","comorbidities","allergies"].forEach((key) => { if (!fields[key]) fields[key] = null; });
    if (fields.height_cm) fields.height_cm = Number(fields.height_cm); if (fields.weight_kg) fields.weight_kg = Number(fields.weight_kg); fields.consent_to_data_processing = fields.consent_to_data_processing === "on";
    button.disabled = true; $("#patient-error").textContent = "";
    try { const patient = await request("/patients", { method:"POST", body:JSON.stringify(fields) }); hideModal(); toast("Пациент создан. Следующий шаг — назначить лечение."); await renderCurrent(); await showPatientDetail(patient); } catch (error) { $("#patient-error").textContent = error.message; $("#patient-error").scrollIntoView({ behavior: "smooth", block: "center" }); } finally { button.disabled = false; }
  });
  $("#logout-button").addEventListener("click", () => { sessionStorage.removeItem("nepres_doctor_token"); state.token = null; state.patients = []; $("#login-form").reset(); setScreen(false); });
  (async () => { if (!state.token) return icon(); try { state.user = await request("/auth/me"); if (state.user.is_admin) throw new Error(); $("#account-name").textContent = state.user.full_name; $("#account-avatar").textContent = state.user.full_name.charAt(0).toUpperCase(); setScreen(true); renderCurrent(); } catch (_) { sessionStorage.removeItem("nepres_doctor_token"); state.token = null; icon(); } })();
})();
