from typing import Protocol

from app.domain.entities import Doctor, Organization, Patient


class OrganizationRepository(Protocol):
    def create(self, name: str) -> Organization: ...
    def get(self, organization_id: int) -> Organization | None: ...
    def list(self) -> list[Organization]: ...
    def update(self, organization_id: int, name: str) -> Organization | None: ...
    def delete(self, organization_id: int) -> bool: ...


class DoctorRepository(Protocol):
    def create(self, organization_id: int, username: str, password_hash: str, full_name: str, email: str | None, is_admin: bool = False) -> Doctor: ...
    def get(self, doctor_id: int) -> Doctor | None: ...
    def get_by_username(self, username: str) -> tuple[Doctor, str] | None: ...
    def list_all(self) -> list[Doctor]: ...
    def list_for_organization(self, organization_id: int) -> list[Doctor]: ...
    def update(self, doctor_id: int, full_name: str | None, email: str | None, is_active: bool | None) -> Doctor | None: ...
    def delete(self, doctor_id: int) -> bool: ...


class PatientRepository(Protocol):
    def create(self, organization_id: int, doctor_id: int, **fields: object) -> Patient: ...
    def get(self, patient_id: int) -> Patient | None: ...
    def list_all(self) -> list[Patient]: ...
    def list_for_organization(self, organization_id: int) -> list[Patient]: ...
    def update(self, patient_id: int, **fields: object) -> Patient | None: ...
    def delete(self, patient_id: int) -> bool: ...
